import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/ReactQueryProvider";
import Header from "./header/page";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/toaster";
import { PostsProvider } from "@/context/PostContext";
import { ValidateUser } from "@/components/authvalidation/Validation";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create ne(xt app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
//  <AuthCheck />
  return (
    <ReactQueryProvider>
      <AuthProvider>
        <PostsProvider>
          <html lang="en">
            <body className={`${inter.className} bg-[#D6D6D6]`}>
              <ValidateUser />
              <Header />
              {children}
              <Toaster />
            </body>
          </html>
        </PostsProvider>
      </AuthProvider>
    </ReactQueryProvider>
  );
}
