import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/ReactQueryProvider";
import Header from "./header/page";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/toaster"
import { PostsProvider } from "@/context/PostContext";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
    
    <ReactQueryProvider>
      <AuthProvider>
       <PostsProvider>
       
      <html lang="en">
      <body className={`${inter.className} bg-[#D6D6D6]` }>
       <Header />
        {children}
        <Toaster />
        
        </body>
    </html>
   
       </PostsProvider>
     </AuthProvider>
    
    </ReactQueryProvider>

     
  );
}
